# Generated by Django 3.0.5 on 2021-06-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='user',
        ),
        migrations.AlterField(
            model_name='tool',
            name='github_link',
            field=models.URLField(null=True, unique=True),
        ),
    ]
